-- =====================================================================
-- Noor Dentofacial Clinic — 0011 Awaiting-payment status
-- =====================================================================
-- Adds an intermediate appointment status between CHECKED_IN and COMPLETED.
--
-- Two-stage visit handoff:
--   CHECKED_IN  --(doctor saves EMR / taps "Mark done")-->  AWAITING_PAYMENT
--   AWAITING_PAYMENT  --(reception completes + collects)-->  COMPLETED (+ bill)
--
-- The doctor only signals they are finished; the bill is still generated by
-- reception via complete_session / completeVisitAndBill, so billing stays a
-- front-desk responsibility.
--
-- Additive + idempotent. ADD VALUE cannot run inside a txn block on older
-- Postgres and the new value can't be used in the SAME statement that adds
-- it, so run this migration on its own (the Supabase SQL editor autocommits).
-- =====================================================================

alter type public.appointment_status
  add value if not exists 'AWAITING_PAYMENT' after 'CHECKED_IN';
